#!/usr/bin/env python3
"""Dependency-free web setup wizard for Linux and Docker deployments."""

from __future__ import annotations

import argparse
import getpass
import html
import os
import re
import sys
import threading
import urllib.parse
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path


SECRET_FIELDS = {"EMAIL_PASSWORD", "AI_API_KEY"}
FIELDS = [
    ("EMAIL_FROM", "发件邮箱", True, "news@example.com"),
    ("EMAIL_PASSWORD", "邮箱密码或授权码", True, ""),
    ("EMAIL_TO", "收件邮箱", True, "多个地址用逗号分隔"),
    ("EMAIL_SMTP_SERVER", "SMTP 服务器", False, "留空则按发件邮箱自动识别"),
    ("EMAIL_SMTP_PORT", "SMTP 端口", False, "留空则按发件邮箱自动识别"),
    ("AI_ANALYSIS_ENABLED", "启用日报 AI 分析", False, "true / false"),
    ("AI_MODEL", "AI 模型", False, "openai/gpt-4o-mini"),
    ("AI_API_KEY", "AI API Key", False, ""),
    ("AI_API_KEY_FILE", "AI API Key 文件", False, "native Linux 可填写服务器上的密钥文件路径"),
    ("AI_API_BASE", "AI API 地址", False, "OpenAI 兼容接口可填写"),
    ("AI_FALLBACK_MODELS", "备用模型", False, "用逗号分隔"),
    ("TZ", "时区", True, "Asia/Shanghai"),
    ("CRAWLER_MINUTE", "每小时采集分钟", False, "0-59"),
    ("MORNING_PUSH_TIME", "早间推送时间", False, "07:00"),
    ("NOON_PUSH_TIME", "午间推送时间", False, "12:00"),
    ("EVENING_PUSH_TIME", "傍晚推送时间", False, "18:00"),
    ("DAILY_SUMMARY_TIME", "全天汇总时间", False, "22:00"),
    ("WEEKLY_WEEKDAY", "周报星期", False, "0=周一，6=周日"),
    ("WEEKLY_HOUR", "周报小时", False, "0-23"),
    ("WEEKLY_MINUTE", "周报分钟", False, "0-59"),
]


def _fields_for(deployment: str) -> list[tuple[str, str, bool, str]]:
    """Return fields supported by the selected deployment target."""
    if deployment == "docker":
        return [field for field in FIELDS if field[0] != "AI_API_KEY_FILE"]
    return FIELDS


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip("'\"")
    return values


def write_env(path: Path, values: dict[str, str], deployment: str = "linux") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by the TrendRadar Lite setup wizard.",
        "STORAGE_BACKEND=local",
    ]
    for key, _label, _required, _hint in _fields_for(deployment):
        value = values.get(key, "").replace("\r", "").replace("\n", "")
        if not value:
            continue
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(path, 0o600)


def render(
    values: dict[str, str],
    errors: list[str] | None = None,
    saved: bool = False,
    deployment: str = "linux",
) -> str:
    sections = {"邮件推送": [], "AI 分析": [], "执行时间": []}
    for key, label, required, hint in _fields_for(deployment):
        value = "" if key in SECRET_FIELDS else values.get(key, "")
        placeholder = "已保存，留空保持不变" if key in SECRET_FIELDS and values.get(key) else hint
        input_type = "password" if key in SECRET_FIELDS else "time" if key.endswith("_PUSH_TIME") or key == "DAILY_SUMMARY_TIME" else "text"
        field = (
            f'<label><span>{html.escape(label)}{" *" if required else ""}</span>'
            f'<input name="{key}" type="{input_type}" '
            f'value="{html.escape(value)}" placeholder="{html.escape(placeholder)}"'
            f'{" required" if required and not values.get(key) else ""}></label>'
        )
        section = "邮件推送" if key.startswith("EMAIL_") else "AI 分析" if key.startswith("AI_") else "执行时间"
        sections[section].append(field)
    section_html = "".join(
        f'<section><h2>{title}</h2>{"".join(fields)}</section>'
        for title, fields in sections.items()
    )
    notice = "<div class=ok>配置已保存，可以关闭此页面。</div>" if saved else ""
    error = ""
    if errors:
        error = "<div class=error>" + "<br>".join(html.escape(item) for item in errors) + "</div>"
    return f"""<!doctype html>
<html lang="zh-CN"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TrendRadar Lite 配置</title>
<style>
body{{font:16px system-ui,sans-serif;max-width:760px;margin:32px auto;padding:0 18px;color:#17202a;background:#f5f7fa}}
main{{background:white;padding:28px;border:1px solid #d9e0e7;border-radius:8px;box-shadow:0 2px 8px #0001}}
h1{{font-size:24px;margin-top:0}} h2{{font-size:17px;margin:0 0 13px}} p{{color:#52606d}} form{{display:grid;gap:24px}}
section{{display:grid;gap:13px}} label{{display:grid;gap:6px;font-weight:600}} input{{font:inherit;padding:10px;border:1px solid #b8c2cc;border-radius:5px}}
button{{font:inherit;padding:11px 16px;background:#1769aa;color:white;border:0;border-radius:5px;cursor:pointer}}
.ok{{padding:12px;background:#e3f6e8;color:#176b35;margin:14px 0}} .error{{padding:12px;background:#fde8e8;color:#a11;margin:14px 0}}
</style><main><h1>TrendRadar Lite 配置</h1>
<p>邮件配置为必填，SMTP 服务器和端口可留空自动识别。AI 分析可选，密码和密钥不会回显。</p>
{notice}{error}<form method="post">{section_html}<button type="submit">保存配置并继续安装</button></form></main></html>"""


def validate(values: dict[str, str], deployment: str = "linux") -> list[str]:
    fields = _fields_for(deployment)
    errors = [f"请填写：{label}" for key, label, required, _hint in fields if required and not values.get(key)]
    if values.get("AI_ANALYSIS_ENABLED", "false").lower() == "true":
        has_key = values.get("AI_API_KEY") or (
            deployment != "docker" and values.get("AI_API_KEY_FILE")
        )
        if not values.get("AI_MODEL") or not has_key:
            key_hint = "AI_API_KEY" if deployment == "docker" else "AI_API_KEY 或 AI_API_KEY_FILE"
            errors.append(f"启用 AI 分析时必须填写 AI_MODEL，以及 {key_hint}")
    if bool(values.get("EMAIL_SMTP_SERVER")) != bool(values.get("EMAIL_SMTP_PORT")):
        errors.append("EMAIL_SMTP_SERVER 和 EMAIL_SMTP_PORT 必须同时填写，或同时留空")
    ranges = {
        "EMAIL_SMTP_PORT": (1, 65535),
        "CRAWLER_MINUTE": (0, 59),
        "WEEKLY_WEEKDAY": (0, 6),
        "WEEKLY_HOUR": (0, 23),
        "WEEKLY_MINUTE": (0, 59),
    }
    for key, (minimum, maximum) in ranges.items():
        if not values.get(key):
            continue
        try:
            number = int(values[key])
        except ValueError:
            errors.append(f"{key} 必须是整数")
            continue
        if not minimum <= number <= maximum:
            errors.append(f"{key} 必须在 {minimum}-{maximum} 之间")
    time_keys = ("MORNING_PUSH_TIME", "NOON_PUSH_TIME", "EVENING_PUSH_TIME", "DAILY_SUMMARY_TIME")
    for key in time_keys:
        if values.get(key) and not re.fullmatch(r"(?:[01]\d|2[0-3]):[0-5]\d", values[key]):
            errors.append(f"{key} 必须使用 HH:MM 格式")
    return errors


def _write_timer(path: Path, description: str, calendars: list[str]) -> None:
    calendars = list(dict.fromkeys(calendars))
    lines = [
        "[Unit]",
        f"Description={description}",
        "",
        "[Timer]",
        *(f"OnCalendar={value}" for value in calendars),
        "Persistent=true",
        "AccuracySec=1min",
        "",
        "[Install]",
        "WantedBy=timers.target",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_systemd_timer(path: Path, values: dict[str, str]) -> None:
    crawler_minute = int(values.get("CRAWLER_MINUTE") or "5")
    push_times = [
        values.get("MORNING_PUSH_TIME", "07:00"),
        values.get("NOON_PUSH_TIME", "12:00"),
        values.get("EVENING_PUSH_TIME", "18:00"),
        values.get("DAILY_SUMMARY_TIME", "22:00"),
    ]
    calendars = [f"*-*-* *:{crawler_minute:02d}:00"]
    calendars.extend(f"*-*-* {value}:00" for value in push_times)
    _write_timer(
        path,
        "Run TrendRadar Lite for hourly collection and configured delivery times",
        calendars,
    )


def write_systemd_weekly_timer(path: Path, values: dict[str, str]) -> None:
    weekdays = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
    weekday = weekdays[int(values.get("WEEKLY_WEEKDAY") or "6")]
    hour = int(values.get("WEEKLY_HOUR") or "12")
    minute = int(values.get("WEEKLY_MINUTE") or "30")
    _write_timer(
        path,
        f"Run TrendRadar Lite weekly report on {weekday}",
        [f"{weekday} *-*-* {hour:02d}:{minute:02d}:00 {values.get('TZ') or 'Asia/Shanghai'}"],
    )


def _section_of(key: str) -> str:
    if key.startswith("EMAIL_"):
        return "邮件推送"
    if key.startswith("AI_"):
        return "AI 分析"
    return "执行时间"


def _prompt_field(
    key: str, label: str, required: bool, hint: str, current: dict[str, str]
) -> str:
    """Prompt one field on a terminal; empty input keeps the current value."""
    is_secret = key in SECRET_FIELDS
    has_current = bool(current.get(key))
    if is_secret and has_current:
        note = "已保存，回车保持不变"
    elif is_secret:
        note = hint
    elif has_current:
        note = f"当前 {current[key]}，回车保持不变"
    else:
        note = hint
    label_text = f"{label}{' *' if required else ''}"
    prompt = f"  {label_text}" + (f"（{note}）" if note else "") + ": "
    entered = (getpass.getpass(prompt) if is_secret else input(prompt)).strip()
    return entered if entered else current.get(key, "")


def configure_terminal(output: Path, deployment: str = "linux") -> None:
    """Interactive terminal setup wizard; a TTY-friendly alternative to the web page."""
    current = read_env(output)
    fields = _fields_for(deployment)
    print("TrendRadar Lite 终端配置向导", flush=True)
    print("邮件为必填（标 *），SMTP 可留空自动识别；AI 可选。直接回车沿用已保存的值。", flush=True)
    while True:
        submitted = dict(current)
        last_section = ""
        for key, label, required, hint in fields:
            section = _section_of(key)
            if section != last_section:
                print(f"\n[{section}]", flush=True)
                last_section = section
            submitted[key] = _prompt_field(key, label, required, hint, current)
        errors = validate(submitted, deployment=deployment)
        if not errors:
            write_env(output, submitted, deployment=deployment)
            print("\n配置已保存，安装将继续。", flush=True)
            return
        print("\n配置有误，请修正后重新填写：", flush=True)
        for item in errors:
            print(f"  - {item}", flush=True)
        print("（已填写的值会保留，回车即可沿用）", flush=True)
        current = submitted


def detect_ssh_target(user: str, host: str, ssh_port: int) -> tuple[str, str, int]:
    connection = os.environ.get("SSH_CONNECTION", "").split()
    if not host and len(connection) == 4:
        host = connection[2]
    if ssh_port == 0 and len(connection) == 4 and connection[3].isdigit():
        ssh_port = int(connection[3])
    login_user = user or os.environ.get("SUDO_USER") or os.environ.get("USER") or getpass.getuser()
    return login_user, host or "server", ssh_port or 22


def ssh_tunnel_command(user: str, host: str, ssh_port: int, setup_port: int) -> str:
    port_option = f" -p {ssh_port}" if ssh_port != 22 else ""
    return f"ssh{port_option} -L {setup_port}:127.0.0.1:{setup_port} {user}@{host}"


def serve(
    output: Path,
    host: str,
    port: int,
    public_port: int,
    ssh_user: str,
    ssh_host: str,
    ssh_port: int,
    deployment: str,
) -> None:
    current = read_env(output)
    done = threading.Event()

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *_args: object) -> None:
            return

        def send_page(self, body: str, status: int = 200) -> None:
            encoded = body.encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(encoded)))
            self.end_headers()
            self.wfile.write(encoded)

        def do_GET(self) -> None:
            self.send_page(render(current, deployment=deployment))

        def do_POST(self) -> None:
            length = int(self.headers.get("Content-Length", "0"))
            form = urllib.parse.parse_qs(self.rfile.read(length).decode("utf-8"), keep_blank_values=True)
            submitted = {
                key: form.get(key, [""])[0].strip()
                for key, *_rest in _fields_for(deployment)
            }
            for key in SECRET_FIELDS:
                if key in submitted and not submitted[key] and current.get(key):
                    submitted[key] = current[key]
            errors = validate(submitted, deployment=deployment)
            if errors:
                self.send_page(render(submitted, errors, deployment=deployment), 400)
                return
            write_env(output, submitted, deployment=deployment)
            self.send_page(render(submitted, saved=True, deployment=deployment))
            done.set()

    server = HTTPServer((host, port), Handler)
    setup_port = public_port or server.server_port
    user, target_host, target_port = detect_ssh_target(ssh_user, ssh_host, ssh_port)
    command = ssh_tunnel_command(user, target_host, target_port, setup_port)
    print(f"配置页面：http://127.0.0.1:{setup_port}/", flush=True)
    print("远程 VPS 请在本机终端直接复制执行：", flush=True)
    print(command, flush=True)
    print("保持该终端运行，再用本机浏览器打开配置页面。", flush=True)
    while not done.is_set():
        server.handle_request()
    server.server_close()


def main() -> int:
    parser = argparse.ArgumentParser(description="TrendRadar Lite configuration wizard")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--public-port", type=int, default=0)
    parser.add_argument("--ssh-user", default="")
    parser.add_argument("--ssh-host", default="")
    parser.add_argument("--ssh-port", type=int, default=0)
    parser.add_argument("--render-systemd-timer", type=Path)
    parser.add_argument("--render-systemd-weekly-timer", type=Path)
    parser.add_argument("--deployment", choices=("linux", "docker"), default="linux")
    parser.add_argument(
        "--mode",
        choices=("auto", "terminal", "web"),
        default="auto",
        help="auto: 有终端走问答，否则起网页；terminal: 强制终端；web: 强制网页",
    )
    parser.add_argument("--terminal", action="store_true", help="等价于 --mode terminal")
    parser.add_argument("--web", action="store_true", help="等价于 --mode web")
    args = parser.parse_args()
    if args.render_systemd_timer:
        write_systemd_timer(args.render_systemd_timer, read_env(args.output))
        return 0
    if args.render_systemd_weekly_timer:
        write_systemd_weekly_timer(args.render_systemd_weekly_timer, read_env(args.output))
        return 0
    mode = args.mode
    if args.terminal:
        mode = "terminal"
    if args.web:
        mode = "web"
    if mode == "auto":
        mode = "terminal" if sys.stdin.isatty() else "web"
    if mode == "terminal":
        try:
            configure_terminal(args.output, args.deployment)
        except EOFError:
            print(
                "终端配置不可用：标准输入已结束或无法交互。"
                "请改用网页配置（--mode web；Docker 安装器会自动发布配置端口）。",
                file=sys.stderr,
                flush=True,
            )
            return 2
        return 0
    serve(
        args.output,
        args.host,
        args.port,
        args.public_port,
        args.ssh_user,
        args.ssh_host,
        args.ssh_port,
        args.deployment,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
