#!/usr/bin/env python3
"""Dependency-free web setup wizard for Linux and Docker deployments."""

from __future__ import annotations

import argparse
import html
import os
import threading
import urllib.parse
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path


SECRET_FIELDS = {"EMAIL_PASSWORD", "AI_API_KEY"}
FIELDS = [
    ("EMAIL_FROM", "发件邮箱", True, "news@example.com"),
    ("EMAIL_PASSWORD", "邮箱密码或授权码", True, ""),
    ("EMAIL_TO", "收件邮箱", True, "多个地址用逗号分隔"),
    ("EMAIL_SMTP_SERVER", "SMTP 服务器", True, "smtp.example.com"),
    ("EMAIL_SMTP_PORT", "SMTP 端口", True, "465"),
    ("AI_ANALYSIS_ENABLED", "启用日报 AI 分析", False, "true / false"),
    ("AI_MODEL", "AI 模型", False, "openai/gpt-4o-mini"),
    ("AI_API_KEY", "AI API Key", False, ""),
    ("AI_API_BASE", "AI API 地址", False, "OpenAI 兼容接口可填写"),
    ("AI_FALLBACK_MODELS", "备用模型", False, "用逗号分隔"),
    ("TZ", "时区", True, "Asia/Shanghai"),
    ("CRAWLER_MINUTE", "每小时采集分钟", False, "0-59"),
    ("WEEKLY_HOUR", "周报小时", False, "0-23"),
    ("WEEKLY_MINUTE", "周报分钟", False, "0-59"),
]


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip("'\"")
    return values


def write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by the TrendRadar Lite setup wizard.",
        "STORAGE_BACKEND=local",
    ]
    for key, _label, _required, _hint in FIELDS:
        value = values.get(key, "").replace("\r", "").replace("\n", "")
        if not value:
            continue
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(path, 0o600)


def render(values: dict[str, str], errors: list[str] | None = None, saved: bool = False) -> str:
    inputs = []
    for key, label, required, hint in FIELDS:
        value = "" if key in SECRET_FIELDS else values.get(key, "")
        placeholder = "已保存，留空保持不变" if key in SECRET_FIELDS and values.get(key) else hint
        inputs.append(
            f'<label><span>{html.escape(label)}{" *" if required else ""}</span>'
            f'<input name="{key}" type="{"password" if key in SECRET_FIELDS else "text"}" '
            f'value="{html.escape(value)}" placeholder="{html.escape(placeholder)}"'
            f'{" required" if required and not values.get(key) else ""}></label>'
        )
    notice = "<div class=ok>配置已保存，可以关闭此页面。</div>" if saved else ""
    error = ""
    if errors:
        error = "<div class=error>" + "<br>".join(html.escape(item) for item in errors) + "</div>"
    return f"""<!doctype html>
<html lang="zh-CN"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TrendRadar Lite 配置</title>
<style>
body{{font:16px system-ui,sans-serif;max-width:760px;margin:32px auto;padding:0 18px;color:#17202a;background:#f5f7fa}}
main{{background:white;padding:28px;border:1px solid #d9e0e7;border-radius:8px;box-shadow:0 2px 8px #0001}}
h1{{font-size:24px;margin-top:0}} p{{color:#52606d}} form{{display:grid;gap:15px}}
label{{display:grid;gap:6px;font-weight:600}} input{{font:inherit;padding:10px;border:1px solid #b8c2cc;border-radius:5px}}
button{{font:inherit;padding:11px 16px;background:#1769aa;color:white;border:0;border-radius:5px;cursor:pointer}}
.ok{{padding:12px;background:#e3f6e8;color:#176b35;margin:14px 0}} .error{{padding:12px;background:#fde8e8;color:#a11;margin:14px 0}}
</style><main><h1>TrendRadar Lite 配置</h1>
<p>邮件配置为必填，AI 分析可选。密码和密钥不会回显。</p>
{notice}{error}<form method="post">{"".join(inputs)}<button type="submit">保存配置并继续安装</button></form></main></html>"""


def validate(values: dict[str, str]) -> list[str]:
    errors = [f"请填写：{label}" for key, label, required, _hint in FIELDS if required and not values.get(key)]
    if values.get("AI_ANALYSIS_ENABLED", "false").lower() == "true":
        if not values.get("AI_MODEL") or not values.get("AI_API_KEY"):
            errors.append("启用 AI 分析时必须填写 AI_MODEL 和 AI_API_KEY")
    ranges = {"EMAIL_SMTP_PORT": (1, 65535), "CRAWLER_MINUTE": (0, 59), "WEEKLY_HOUR": (0, 23), "WEEKLY_MINUTE": (0, 59)}
    for key, (minimum, maximum) in ranges.items():
        if not values.get(key):
            continue
        try:
            number = int(values[key])
        except ValueError:
            errors.append(f"{key} 必须是整数")
            continue
        if not minimum <= number <= maximum:
            errors.append(f"{key} 必须在 {minimum}-{maximum} 之间")
    return errors


def serve(output: Path, host: str, port: int) -> None:
    current = read_env(output)
    done = threading.Event()

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *_args: object) -> None:
            return

        def send_page(self, body: str, status: int = 200) -> None:
            encoded = body.encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(encoded)))
            self.end_headers()
            self.wfile.write(encoded)

        def do_GET(self) -> None:
            self.send_page(render(current))

        def do_POST(self) -> None:
            length = int(self.headers.get("Content-Length", "0"))
            form = urllib.parse.parse_qs(self.rfile.read(length).decode("utf-8"), keep_blank_values=True)
            submitted = {key: form.get(key, [""])[0].strip() for key, *_rest in FIELDS}
            for key in SECRET_FIELDS:
                if not submitted[key] and current.get(key):
                    submitted[key] = current[key]
            errors = validate(submitted)
            if errors:
                self.send_page(render(submitted, errors), 400)
                return
            write_env(output, submitted)
            self.send_page(render(submitted, saved=True))
            done.set()

    server = HTTPServer((host, port), Handler)
    actual_port = server.server_port
    print(f"配置页面：http://{host}:{actual_port}/", flush=True)
    print(f"远程 VPS 请另开终端执行：ssh -L {actual_port}:127.0.0.1:{actual_port} user@server", flush=True)
    print("然后在本机浏览器打开上面的地址。", flush=True)
    while not done.is_set():
        server.handle_request()
    server.server_close()


def main() -> int:
    parser = argparse.ArgumentParser(description="TrendRadar Lite configuration wizard")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args()
    serve(args.output, args.host, args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
